// Tourist Safety & Smart Monitoring System (TSMS) - Mock Database & Translations
(function () {
  const TSMS_MOCK_DATA = {
    // Languages supported: English, Spanish, French, Japanese, Hindi
    translations: {
      en: {
        title: "TSMS | Smart Tourist Safety",
        heroTitle: "Tourist Safety & Smart Monitoring System",
        heroSubtitle: "Experience travel with peace of mind. Secure digital identity, intelligent behavior monitoring, and instant emergency response at your fingertips.",
        navHome: "Home",
        navTourist: "Tourist Portal",
        navAdmin: "Admin Control Center",
        roleSelector: "Switch View Mode:",
        touristLoginTab: "Tourist Login",
        registerTab: "Register",
        touristLoginTitle: "Tourist Portal Login",
        touristLoginSub: "Access your TSMS Safety Pass and Emergency Console",
        touristIdEmail: "Tourist ID / Email Address",
        password: "Password",
        signInBtn: "Sign In to Tourist Portal",
        adminLoginTitle: "Admin Portal Login",
        adminLoginSub: "Command & Control Access",
        adminUsername: "Admin Username",
        // Welcome card
        welcomeTitle: "Welcome to TSMS",
        welcomeSubtitle: "Enter your name to get started. We'll check if you're already registered.",
        welcomeNewBtn: "New Registration →",
        welcomeReturnBtn: "I'm Returning",
        welcomeNote: "Your details are encrypted and shared only with emergency responders.",
        registerTitle: "Tourist Safety Registration",
        registerSubtitle: "Generate your secure digital identity and activate active safety monitoring.",
        fullName: "Full Name",
        nationality: "Nationality",
        passportNo: "Passport Number",
        visaNo: "Visa Number",
        visaExpiry: "Visa Expiration Date",
        emergencyContactName: "Emergency Contact Name",
        emergencyContactPhone: "Emergency Contact Phone",
        registerBtn: "Register & Issue Digital ID",
        idCardTitle: "Verified Digital Identity",
        idCardSubtitle: "Official Smart Safety Pass",
        touristId: "Tourist ID",
        statusLabel: "Safety Status",
        statusSafe: "Safe",
        statusDistress: "In Distress",
        statusWarning: "AI Warning",
        statusInactive: "Inactive",
        downloadId: "Download ID Card",
        printId: "Print Smart Pass",
        sosTitle: "Emergency SOS Console",
        sosSubtitle: "IN EMERGENCY: Press and hold the SOS button for 3 seconds to alert local authorities.",
        sosButtonText: "SOS HELP",
        sosActiveText: "SOS ACTIVE",
        sosCancelText: "Cancel SOS (Countdown: {sec}s)",
        sosTypeLabel: "Select Emergency Type:",
        sosMedical: "Medical Emergency",
        sosAccident: "Accident / Crash",
        sosSecurity: "Security Threat / Theft",
        sosOther: "Other Danger",
        activityTitle: "Log Tourist Activity",
        activitySubtitle: "Help the safety AI understand your context to prevent false alerts.",
        activitySelect: "Current Activity",
        actHiking: "Mountain Trekking / Hiking",
        actExploring: "City Walk / Sightseeing",
        actSwimming: "Water Sports / Swimming",
        actResting: "Resting / At Hotel",
        actTransit: "In Transit / Driving",
        logActivityBtn: "Update Active Status",
        privacyTitle: "Privacy & Data Encryption",
        privacySubtitle: "Your data is secured locally using browser-level sandbox encryption.",
        privacyText: "Your personal details, live coordinates, and check-in logs are encrypted at rest. Location history is purged automatically every 48 hours. Only verified law enforcement and emergency dispatchers can access your details during an active SOS event.",
        wearableTitle: "Smart Wearable Device Integration",
        wearableSubtitle: "Link smartwatches to monitor vitals in high-risk zones.",
        wearablePairBtn: "Pair Smartwatch",
        wearableUnpairBtn: "Disconnect Device",
        wearableStatusConnected: "Wearable Active: Synced",
        wearableSelectLabel: "Choose Device:",
        wearableHighRiskMode: "High-Risk Geofence Automation",
        wearableHighRiskDesc: "Enables automatic fall/heart rate emergency triggers.",
        vaultTitle: "Secure Database Encryption Vault",
        vaultSubtitle: "Real-time sandbox data storage audit at rest.",
        vaultInspectBtn: "Inspect Storage Vault",
        vaultLabelRaw: "Encrypted Storage (AES-256 Mock Cipher):",
        vaultLabelDecrypted: "Authorized Decrypted Plaintext:",
        
        // Admin Strings
        adminConsole: "Command & Control Console",
        adminSubtitle: "Real-time emergency monitoring, geofence status, and AI threat warnings.",
        metricTourists: "Active Tourists",
        metricSOS: "Active Emergencies",
        metricRisk: "AI Threat Flags",
        metricIndex: "Region Safety Score",
        liveSosFeed: "Live Emergency Dispatch",
        noSosAlerts: "No active emergencies. System operating normally.",
        dispatchBtn: "Dispatch First Responder",
        resolveBtn: "Resolve & Close Incident",
        aiLogs: "AI Behavior Detection Logs",
        aiAnalysisActive: "AI engine analyzing telemetry...",
        touristDirectory: "Tourist Safety Registry",
        exportReport: "Export Reports",
        sirenBtn: "🔊 Siren Sound",
        mapLegend: "Interactive Geofence & Tracker Map",
        mapLabelSeaside: "Seaside Resort",
        mapLabelCentral: "Central City Sector",
        mapLabelMountain: "Mountain Ridge",
        mapLabelCanyon: "High-Risk Canyon",
        mapLabelMarina: "Deep Water Marina",
        dispatchSub: "Direct coordination channel with active SOS callers.",
        exportSub: "Review safety index stats and download regulatory operational logs.",
        chartIncidents: "Incidents By Type",
        chartSafety: "Safety Status Distribution",
        btnDownloadCsv: "Download CSV Registry",
        btnDownloadTxt: "Download Audit Text Log",
        kycTitle: "🪪 KYC Identity Verification Queue",
        kycSubtitle: "Review, approve or reject tourist identity submissions.",
        kycBtnRefresh: "🔄 Refresh",
        kycSearchPlace: "🔍 Search name or passport...",
        kycFilterAll: "All",
        kycFilterPending: "Pending",
        kycFilterVerified: "Verified",
        kycFilterRejected: "Rejected",
        kycFilterManual: "Manual Review",
        kycThId: "Tourist ID",
        kycThName: "Full Name",
        kycThPassport: "Passport No",
        kycThSubmitted: "Submitted At",
        kycThOcr: "OCR Status",
        kycThKyc: "KYC Status",
        kycThActions: "Actions",
        kycLoading: "Loading KYC submissions...",
        triggerSosSub: "Click to Trigger",
        sosTransmitting: "Distress Telemetry Transmitting...",
        notePlaceholder: "Write an emergency note or custom status update (Optional)...",
        kycDetailNameLbl: "Full Name",
        kycDetailPassLbl: "Passport No",
        kycDetailDobLbl: "Date of Birth",
        kycDetailNatLbl: "Nationality",
        kycDetailExpLbl: "Expiry Date",
        kycDetailIssLbl: "Issuing Country",
        kycDetailNoOcr: "No OCR data available.",
        kycBtnView: "View →",
        viewMap: "Live Safety Map",
        mapLegend: "Interactive Geofence & Tracker Map",
        searchPlaceholder: "Search by ID, name, or nationality...",
        closeDetails: "Close Panel"
      },
      es: {
        title: "TSMS | Seguridad Turística Inteligente",
        heroTitle: "Sistema de Seguridad y Monitoreo Inteligente para Turistas",
        heroSubtitle: "Viaje con tranquilidad. Identidad digital segura, monitoreo inteligente del comportamiento y respuesta instantánea ante emergencias.",
        navHome: "Inicio",
        navTourist: "Portal del Turista",
        navAdmin: "Centro de Control Administrativo",
        roleSelector: "Cambiar vista:",
        touristLoginTab: "Inicio de Turista",
        registerTab: "Registro (KYC)",
        touristLoginTitle: "Inicio del Portal de Turista",
        touristLoginSub: "Acceda a su Pase de Seguridad TSMS y Consola de Emergencia",
        touristIdEmail: "ID de Turista / Correo Electrónico",
        password: "Contraseña",
        signInBtn: "Ingresar al Portal",
        adminLoginTitle: "Inicio del Portal Administrativo",
        adminLoginSub: "Acceso de Comando y Control",
        adminUsername: "Nombre de Usuario",
        // Welcome card
        welcomeTitle: "Bienvenido a TSMS",
        welcomeSubtitle: "Ingrese su nombre para comenzar. Verificaremos si ya está registrado.",
        welcomeNewBtn: "Nuevo Registro →",
        welcomeReturnBtn: "Soy Visitante Frecuente",
        welcomeNote: "Sus datos están encriptados y solo los comparten con socorristas de emergencia.",
        registerTitle: "Registro de Seguridad Turística",
        registerSubtitle: "Genere su identidad digital segura y active el monitoreo de seguridad.",
        fullName: "Nombre Completo",
        nationality: "Nacionalidad",
        passportNo: "Número de Pasaporte",
        visaNo: "Número de Visa",
        visaExpiry: "Fecha de Vencimiento de Visa",
        emergencyContactName: "Nombre de Contacto de Emergencia",
        emergencyContactPhone: "Teléfono de Contacto de Emergencia",
        registerBtn: "Registrarse y Emitir Identificación Digital",
        idCardTitle: "Identidad Digital Verificada",
        idCardSubtitle: "Pase de Seguridad Inteligente Oficial",
        touristId: "ID de Turista",
        statusLabel: "Estado de Seguridad",
        statusSafe: "Seguro",
        statusDistress: "En Apuros",
        statusWarning: "Advertencia de IA",
        statusInactive: "Inactivo",
        downloadId: "Descargar Identificación",
        printId: "Imprimir Pase",
        sosTitle: "Consola SOS de Emergencia",
        sosSubtitle: "EN CASO DE EMERGENCIA: Mantenga presionado el botón SOS por 3 segundos para alertar.",
        sosButtonText: "SOS AYUDA",
        sosActiveText: "SOS ACTIVO",
        sosCancelText: "Cancelar SOS (Cuenta regresiva: {sec}s)",
        sosTypeLabel: "Seleccione Tipo de Emergencia:",
        sosMedical: "Emergencia Médica",
        sosAccident: "Accidente / Choque",
        sosSecurity: "Amenaza de Seguridad / Robo",
        sosOther: "Otro Peligro",
        activityTitle: "Registrar Actividad del Turista",
        activitySubtitle: "Ayude a la IA a comprender su contexto para evitar falsas alertas.",
        activitySelect: "Actividad Actual",
        actHiking: "Senderismo / Trekking",
        actExploring: "Caminata por la Ciudad",
        actSwimming: "Deportes Acuáticos",
        actResting: "Descansando / En el Hotel",
        actTransit: "En Tránsito / Conduciendo",
        logActivityBtn: "Actualizar Estado Activo",
        privacyTitle: "Privacidad y Encriptación de Datos",
        privacySubtitle: "Sus datos están protegidos localmente mediante encriptación sandbox.",
        privacyText: "Sus datos personales, coordenadas en vivo y registros de check-in están encriptados. El historial de ubicación se purga automáticamente cada 48 horas. Solo el personal de emergencia verificado puede acceder a sus datos en caso de SOS activo.",
        wearableTitle: "Integración de Dispositivos Usables",
        wearableSubtitle: "Vincule relojes inteligentes para monitorear signos vitales en zonas de alto riesgo.",
        wearablePairBtn: "Vincular Reloj Inteligente",
        wearableUnpairBtn: "Desconectar Dispositivo",
        wearableStatusConnected: "Usable Activo: Sincronizado",
        wearableSelectLabel: "Seleccionar Dispositivo:",
        wearableHighRiskMode: "Automatización de Geocercas de Alto Riesgo",
        wearableHighRiskDesc: "Permite activar alarmas automáticas por caídas o picos de frecuencia cardíaca.",
        vaultTitle: "Bóveda de Encriptación de Datos",
        vaultSubtitle: "Auditoría en tiempo real de datos almacenados en reposo.",
        vaultInspectBtn: "Inspeccionar Bóveda de Seguridad",
        vaultLabelRaw: "Almacenamiento Encriptado (Cifrado AES-256):",
        vaultLabelDecrypted: "Texto Plano Descifrado Autorizado:",
        
        // Admin
        adminConsole: "Consola de Comando y Control",
        adminSubtitle: "Monitoreo de emergencias en tiempo real, estado de geocercas y alertas de IA.",
        metricTourists: "Turistas Activos",
        metricSOS: "Emergencias Activas",
        metricRisk: "Alertas de Amenaza de IA",
        metricIndex: "Puntuación de Seguridad",
        liveSosFeed: "Despacho de Emergencia en Vivo",
        noSosAlerts: "No hay emergencias activas. Sistema operando normalmente.",
        dispatchBtn: "Despachar Socorristas",
        resolveBtn: "Resolver y Cerrar Incidente",
        aiLogs: "Registros de Detección de IA",
        aiAnalysisActive: "Motor de IA analizando telemetría...",
        touristDirectory: "Registro de Seguridad Turística",
        exportReport: "Exportar Informes",
        sirenBtn: "🔊 Sonido de Sirena",
        mapLegend: "Mapa Interactivo de Geovalla y Rastreo",
        mapLabelSeaside: "Resort Junto al Mar",
        mapLabelCentral: "Sector Central de la Ciudad",
        mapLabelMountain: "Cresta de la Montaña",
        mapLabelCanyon: "Cañón de Alto Riesgo",
        mapLabelMarina: "Marina de Aguas Profundas",
        dispatchSub: "Canal de coordinación directo con las personas que llaman al SOS.",
        exportSub: "Revise las estadísticas del índice de seguridad y descargue los registros operativos.",
        chartIncidents: "Incidentes por Tipo",
        chartSafety: "Distribución del Estado de Seguridad",
        btnDownloadCsv: "Descargar Registro CSV",
        btnDownloadTxt: "Descargar Registro de Auditoría",
        kycTitle: "🪪 Cola de Verificación de Identidad KYC",
        kycSubtitle: "Revisar, aprobar o rechazar envíos de identidad de turistas.",
        kycBtnRefresh: "🔄 Actualizar",
        kycSearchPlace: "🔍 Buscar nombre o pasaporte...",
        kycFilterAll: "Todos",
        kycFilterPending: "Pendiente",
        kycFilterVerified: "Verificado",
        kycFilterRejected: "Rechazado",
        kycFilterManual: "Revisión Manual",
        kycThId: "ID del Turista",
        kycThName: "Nombre Completo",
        kycThPassport: "Pasaporte No",
        kycThSubmitted: "Enviado En",
        kycThOcr: "Estado OCR",
        kycThKyc: "Estado KYC",
        kycThActions: "Acciones",
        kycLoading: "Cargando envíos KYC...",
        triggerSosSub: "Haz clic para activar",
        sosTransmitting: "Transmitiendo telemetría de emergencia...",
        notePlaceholder: "Escriba una nota de emergencia o actualización de estado (Opcional)...",
        kycDetailNameLbl: "Nombre Completo",
        kycDetailPassLbl: "Pasaporte No",
        kycDetailDobLbl: "Fecha de Nacimiento",
        kycDetailNatLbl: "Nacionalidad",
        kycDetailExpLbl: "Fecha de Expiración",
        kycDetailIssLbl: "País Emisor",
        kycDetailNoOcr: "No hay datos OCR disponibles.",
        kycBtnView: "Ver →",
        viewMap: "Mapa de Seguridad en Vivo",
        mapLegend: "Mapa Interactivo de Seguimiento y Geocercas",
        searchPlaceholder: "Buscar por ID, nombre o nacionalidad...",
        closeDetails: "Cerrar Panel"
      },
      fr: {
        title: "TSMS | Sécurité Touristique Intelligente",
        heroTitle: "Système de Sécurité et de Surveillance des Touristes",
        heroSubtitle: "Voyagez l'esprit tranquille. Identité numérique sécurisée, surveillance intelligente et réponse d'urgence instantanée.",
        navHome: "Accueil",
        navTourist: "Portail Touriste",
        navAdmin: "Centre de Contrôle Admin",
        roleSelector: "Changer de Mode:",
        // Welcome card
        welcomeTitle: "Bienvenue sur TSMS",
        welcomeSubtitle: "Entrez votre nom pour commencer. Nous vérifierons si vous êtes déjà enregistré.",
        welcomeNewBtn: "Nouvelle Inscription →",
        welcomeReturnBtn: "Je Reviens",
        welcomeNote: "Vos données sont cryptées et partagées uniquement avec les secouristes.",
        registerTitle: "Enregistrement Sécurité Touristique",
        registerSubtitle: "Générez votre identité numérique sécurisée et activez la surveillance active.",
        fullName: "Nom Complet",
        nationality: "Nationalité",
        passportNo: "Numéro de Passeport",
        visaNo: "Numéro de Visa",
        visaExpiry: "Date d'expiration du Visa",
        emergencyContactName: "Contact d'Urgence (Nom)",
        emergencyContactPhone: "Contact d'Urgence (Téléphone)",
        registerBtn: "S'enregistrer & Obtenir l'ID",
        idCardTitle: "Identité Numérique Vérifiée",
        idCardSubtitle: "Passeport Sécurité Intelligent Officiel",
        touristId: "ID Touriste",
        statusLabel: "Statut de Sécurité",
        statusSafe: "Sûr",
        statusDistress: "En Détresse",
        statusWarning: "Alerte IA",
        statusInactive: "Inactif",
        downloadId: "Télécharger la Carte",
        printId: "Imprimer la Carte",
        sosTitle: "Console SOS d'Urgence",
        sosSubtitle: "EN CAS D'URGENCE: Maintenez le bouton SOS enfoncé pendant 3 secondes pour alerter.",
        sosButtonText: "SOS AIDE",
        sosActiveText: "SOS ACTIF",
        sosCancelText: "Annuler SOS (Compte à rebours: {sec}s)",
        sosTypeLabel: "Sélectionnez le Type d'Urgence:",
        sosMedical: "Urgence Médicale",
        sosAccident: "Accident / Collision",
        sosSecurity: "Menace Sécurité / Vol",
        sosOther: "Autre Danger",
        activityTitle: "Enregistrer l'Activité",
        activitySubtitle: "Aidez l'IA à comprendre votre contexte pour éviter les fausses alertes.",
        activitySelect: "Activité Actuelle",
        actHiking: "Randonnée / Trekking",
        actExploring: "Visite de la Ville",
        actSwimming: "Sports Nautiques / Baignade",
        actResting: "Repos / À l'Hôtel",
        actTransit: "En Transit / En Voiture",
        logActivityBtn: "Mettre à Jour le Statut",
        privacyTitle: "Confidentialité & Cryptage",
        privacySubtitle: "Vos données sont sécurisées localement par cryptage.",
        privacyText: "Vos informations personnelles, coordonnées GPS en direct et historiques sont cryptés. L'historique des positions est purgé toutes les 48 heures. Seuls les agents d'urgence peuvent accéder à vos données lors d'un SOS actif.",
        wearableTitle: "Intégration d'Objets Connectés",
        wearableSubtitle: "Associez des montres intelligentes pour suivre les constantes en zone à risque.",
        wearablePairBtn: "Associer la Montre",
        wearableUnpairBtn: "Déconnecter l'Appareil",
        wearableStatusConnected: "Objet Connecté Actif: Synchronisé",
        wearableSelectLabel: "Choisir l'Appareil:",
        wearableHighRiskMode: "Automatisation Zones à Haut Risque",
        wearableHighRiskDesc: "Active les déclenchements d'urgence automatiques en cas de chute ou pic cardiaque.",
        vaultTitle: "Coffre-fort de Cryptage de Données",
        vaultSubtitle: "Audit de stockage des données au repos en temps réel.",
        vaultInspectBtn: "Inspecter le Coffre-fort",
        vaultLabelRaw: "Stockage Crypté (Chiffrement AES-256):",
        vaultLabelDecrypted: "Texte en Clair Décrypté Autorisé:",
        
        // Admin
        adminConsole: "Console de Commandement & Contrôle",
        adminSubtitle: "Surveillance d'urgence en temps réel, géorepérage et menaces détectées par l'IA.",
        metricTourists: "Touristes Actifs",
        metricSOS: "Urgences Actives",
        metricRisk: "Alertes Risque IA",
        metricIndex: "Indice de Sécurité",
        liveSosFeed: "Gestion des Urgences en Direct",
        noSosAlerts: "Aucune urgence en cours. Fonctionnement normal.",
        dispatchBtn: "Déployer les Secours",
        resolveBtn: "Résoudre & Fermer l'Incident",
        aiLogs: "Journal d'Analyse IA",
        aiAnalysisActive: "Analyse de télémétrie par l'IA en cours...",
        touristDirectory: "Registre des Touristes",
        exportReport: "Exporter les Rapports",
        sirenBtn: "🔊 Son de Sirène",
        mapLegend: "Carte Interactive de Géoclôture et Suivi",
        mapLabelSeaside: "Station Balnéaire",
        mapLabelCentral: "Secteur Central de la Ville",
        mapLabelMountain: "Crête de la Montagne",
        mapLabelCanyon: "Canyon à Haut Risque",
        mapLabelMarina: "Marina en Eau Profonde",
        dispatchSub: "Canal de coordination direct avec les appelants SOS actifs.",
        exportSub: "Consultez les statistiques de sécurité et téléchargez les journaux opérationnels.",
        chartIncidents: "Incidents par Type",
        chartSafety: "Répartition de l'État de Sécurité",
        btnDownloadCsv: "Télécharger le Registre CSV",
        btnDownloadTxt: "Télécharger le Journal d'Audit Textuel",
        kycTitle: "🪪 File d'Attente de Vérification d'Identité KYC",
        kycSubtitle: "Examiner, approuver ou rejeter les soumissions d'identité.",
        kycBtnRefresh: "🔄 Rafraîchir",
        kycSearchPlace: "🔍 Rechercher nom ou passeport...",
        kycFilterAll: "Tous",
        kycFilterPending: "En Attente",
        kycFilterVerified: "Vérifié",
        kycFilterRejected: "Rejeté",
        kycFilterManual: "Examen Manuel",
        kycThId: "ID du Touriste",
        kycThName: "Nom Complet",
        kycThPassport: "N° Passeport",
        kycThSubmitted: "Soumis Le",
        kycThOcr: "Statut OCR",
        kycThKyc: "Statut KYC",
        kycThActions: "Actions",
        kycLoading: "Chargement des soumissions KYC...",
        triggerSosSub: "Cliquez pour déclencher",
        sosTransmitting: "Transmission de télémétrie de détresse...",
        notePlaceholder: "Rédigez une note d'urgence ou de statut (Optionnel)...",
        kycDetailNameLbl: "Nom Complet",
        kycDetailPassLbl: "N° Passeport",
        kycDetailDobLbl: "Date de Naissance",
        kycDetailNatLbl: "Nationalité",
        kycDetailExpLbl: "Date d'Expiration",
        kycDetailIssLbl: "Pays Émetteur",
        kycDetailNoOcr: "Aucune donnée OCR disponible.",
        kycBtnView: "Voir →",
        viewMap: "Carte de Sécurité en Direct",
        mapLegend: "Carte Interactive de Suivi et Géorepérage",
        searchPlaceholder: "Rechercher par ID, nom...",
        closeDetails: "Fermer le Panneau"
      },
      ja: {
        title: "TSMS | スマート観光客安全システム",
        heroTitle: "観光客安全＆スマート監視システム",
        heroSubtitle: "安心安全な旅行を。セキュリティで保護されたデジタルID、AIによる行動分析、そして迅速な緊急通報システムを提供します。",
        navHome: "ホーム",
        navTourist: "観光客ポータル",
        navAdmin: "管理者センター",
        roleSelector: "表示モード切替:",
        // Welcome card
        welcomeTitle: "TSMSへようこそ",
        welcomeSubtitle: "安心の旅を始めましょう。お名前を入力してください。",
        welcomeNewBtn: "新規登録 →",
        welcomeReturnBtn: "再度お越しの方",
        welcomeNote: "個人情報は暗号化され、緊急対応者にのみ共有されます。",
        registerTitle: "安全管理への登録",
        registerSubtitle: "デジタル身分証明書を発行し、スマート安全見守り機能を有効化します。",
        fullName: "氏名",
        nationality: "国籍",
        passportNo: "パスポート番号",
        visaNo: "ビザ番号",
        visaExpiry: "ビザ有効期限",
        emergencyContactName: "緊急連絡先氏名",
        emergencyContactPhone: "緊急連絡先電話番号",
        registerBtn: "登録してデジタルIDを発行",
        idCardTitle: "確認済みデジタルID",
        idCardSubtitle: "公式スマート安全パス",
        touristId: "観光客ID",
        statusLabel: "安全ステータス",
        statusSafe: "安全",
        statusDistress: "遭難・SOS中",
        statusWarning: "AI警告あり",
        statusInactive: "未検出",
        downloadId: "IDカードをダウンロード",
        printId: "スマートパスを印刷",
        sosTitle: "緊急SOSコンソール",
        sosSubtitle: "緊急事態：SOSボタンを3秒間長押しすると、直ちに現地当局に通報されます。",
        sosButtonText: "SOS 救助",
        sosActiveText: "SOS 発信中",
        sosCancelText: "キャンセル (残り {sec} 秒)",
        sosTypeLabel: "緊急事態のタイプを選択:",
        sosMedical: "医療緊急事態",
        sosAccident: "事故・衝突",
        sosSecurity: "防犯・盗難脅威",
        sosOther: "その他の危険",
        activityTitle: "活動内容の記録",
        activitySubtitle: "誤警告を防ぐため、AIに現在の状況を知らせます。",
        activitySelect: "現在の活動",
        actHiking: "登山・ハイキング",
        actExploring: "市内観光・街歩き",
        actSwimming: "マリンスポーツ・水泳",
        actResting: "休息・ホテル滞在",
        actTransit: "移動中・運転中",
        logActivityBtn: "活動ステータスを更新",
        privacyTitle: "プライバシーとデータ暗号化",
        privacySubtitle: "データはブラウザの暗号化によって保護されています。",
        privacyText: "個人情報、現在地情報、チェックイン履歴は厳重に暗号化されます。位置情報は48時間後に自動削除されます。SOS発信中のみ、確認済みの救急・警察機関がデータにアクセス可能です。",
        wearableTitle: "スマートウェアラブル機器の連携",
        wearableSubtitle: "高リスク地域でのバイタル監視のためにスマートウォッチを連携します。",
        wearablePairBtn: "ウォッチをペアリング",
        wearableUnpairBtn: "ペアリング解除",
        wearableStatusConnected: "ウェアラブル連携中: 同期完了",
        wearableSelectLabel: "デバイス選択:",
        wearableHighRiskMode: "高リスク地域ジオフェンス自動化",
        wearableHighRiskDesc: "転倒検出や心拍数スパイクによる自動SOS発信を有効にします。",
        vaultTitle: "暗号化データベース・ボルト",
        vaultSubtitle: "保管中データのリアルタイム暗号化監査。",
        vaultInspectBtn: "暗号化ボルトを監査",
        vaultLabelRaw: "暗号化ストレージ (AES-256模擬暗号):",
        vaultLabelDecrypted: "権限付与デコード平文:",
        
        // Admin
        adminConsole: "指令コントロールセンター",
        adminSubtitle: "リアルタイムの緊急監視、ジオフェンスステータス、およびAIによる脅威検知ログ。",
        metricTourists: "活動中の観光客",
        metricSOS: "対応中の緊急事態",
        metricRisk: "AI警戒フラグ",
        metricIndex: "地域安全指数",
        liveSosFeed: "緊急指令フィード",
        noSosAlerts: "現在緊急事態はありません。正常に稼働しています。",
        dispatchBtn: "対応部隊を派遣",
        resolveBtn: "インシデントを解決・終了",
        aiLogs: "AI行動検知ログ",
        aiAnalysisActive: "AIエンジンによるテレメトリ分析中...",
        touristDirectory: "観光客安全登録簿",
        exportReport: "レポートを出力",
        sirenBtn: "🔊 サイレン音",
        mapLegend: "インタラクティブ・ジオフェンス＆トラッカーマップ",
        mapLabelSeaside: "シーサイドリゾート",
        mapLabelCentral: "中央都市セクター",
        mapLabelMountain: "山の尾根",
        mapLabelCanyon: "ハイリスクキャニオン",
        mapLabelMarina: "深水マリーナ",
        dispatchSub: "アクティブなSOS発信者との直接調整チャネル。",
        exportSub: "安全インデックス統計を確認し、運用ログをダウンロードします。",
        chartIncidents: "タイプ別インシデント",
        chartSafety: "安全状態の分布",
        btnDownloadCsv: "CSVレジストリをダウンロード",
        btnDownloadTxt: "監査テキストログをダウンロード",
        kycTitle: "🪪 KYC 身元確認キュー",
        kycSubtitle: "観光客の身元提出を審査、承認、または拒否します。",
        kycBtnRefresh: "🔄 更新",
        kycSearchPlace: "🔍 名前またはパスポートを検索...",
        kycFilterAll: "すべて",
        kycFilterPending: "保留中",
        kycFilterVerified: "確認済み",
        kycFilterRejected: "拒否",
        kycFilterManual: "手動審査",
        kycThId: "観光客ID",
        kycThName: "フルネーム",
        kycThPassport: "パスポート番号",
        kycThSubmitted: "提出日",
        kycThOcr: "OCR ステータス",
        kycThKyc: "KYC ステータス",
        kycThActions: "アクション",
        kycLoading: "KYCの提出物を読み込んでいます...",
        triggerSosSub: "クリックしてトリガー",
        sosTransmitting: "遭難テレメトリーを送信中...",
        notePlaceholder: "緊急メモやステータス更新を記入してください（任意）...",
        kycDetailNameLbl: "フルネーム",
        kycDetailPassLbl: "パスポート番号",
        kycDetailDobLbl: "生年月日",
        kycDetailNatLbl: "国籍",
        kycDetailExpLbl: "有効期限",
        kycDetailIssLbl: "発行国",
        kycDetailNoOcr: "OCRデータは利用できません。",
        kycBtnView: "表示 →",
        viewMap: "ライブ安全マップ",
        mapLegend: "インタラクティブ・ジオフェンス＆追跡マップ",
        searchPlaceholder: "ID、氏名、国籍で検索...",
        closeDetails: "閉じる"
      },
      hi: {
        title: "TSMS | स्मार्ट पर्यटक सुरक्षा",
        heroTitle: "पर्यटक सुरक्षा एवं स्मार्ट मॉनिटरिंग प्रणाली",
        heroSubtitle: "निश्चिंत होकर यात्रा का आनंद लें। सुरक्षित डिजिटल पहचान, एआई-आधारित व्यवहार निगरानी और तत्काल आपातकालीन सहायता उपलब्ध।",
        navHome: "मुख्य पृष्ठ",
        navTourist: "पर्यटक पोर्टल",
        navAdmin: "प्रशासनिक नियंत्रण केंद्र",
        roleSelector: "दृश्य बदलें:",
        // Welcome card
        welcomeTitle: "TSMS में आपका स्वागत है",
        welcomeSubtitle: "शुरू करने के लिए अपना नाम दर्ज करें। हम जांचेंगे कि आप पहले से पंजीकृत हैं या नहीं।",
        welcomeNewBtn: "नया पंजीकरण →",
        welcomeReturnBtn: "मैं वापस आया हूँ",
        welcomeNote: "आपका विवरण एन्क्रिप्ट है और केवल आपातकालीन सेवाओं से साझा किया जाता है।",
        registerTitle: "पर्यटक सुरक्षा पंजीकरण",
        registerSubtitle: "अपनी सुरक्षित डिजिटल पहचान बनाएं और सुरक्षा ट्रैकिंग चालू करें।",
        fullName: "पूरा नाम",
        nationality: "राष्ट्रीयता",
        passportNo: "पासपोर्ट नंबर",
        visaNo: "वीजा नंबर",
        visaExpiry: "वीजा समाप्ति तिथि",
        emergencyContactName: "आपातकालीन संपर्क का नाम",
        emergencyContactPhone: "आपातकालीन संपर्क नंबर",
        registerBtn: "पंजीकरण करें और डिजिटल आईडी प्राप्त करें",
        idCardTitle: "सत्यापित डिजिटल पहचान",
        idCardSubtitle: "आधिकारिक स्मार्ट सुरक्षा पास",
        touristId: "पर्यटक आईडी",
        statusLabel: "सुरक्षा स्थिति",
        statusSafe: "सुरक्षित",
        statusDistress: "संकट में",
        statusWarning: "एआई चेतावनी",
        statusInactive: "निष्क्रिय",
        downloadId: "आईडी डाउनलोड करें",
        printId: "स्मार्ट पास प्रिंट करें",
        sosTitle: "आपातकालीन एसओएस कंसोल",
        sosSubtitle: "आपातकाल में: अधिकारियों को सतर्क करने के लिए एसओएस बटन को 3 सेकंड तक दबाकर रखें।",
        sosButtonText: "एसओएस सहायता",
        sosActiveText: "एसओएस सक्रिय है",
        sosCancelText: "एसओएस रद्द करें ({sec} सेकेंड)",
        sosTypeLabel: "आपातकाल प्रकार चुनें:",
        sosMedical: "चिकित्सा आपातकाल",
        sosAccident: "दुर्घटना / टक्कर",
        sosSecurity: "सुरक्षा खतरा / चोरी",
        sosOther: "अन्य खतरा",
        activityTitle: "पर्यटक गतिविधि दर्ज करें",
        activitySubtitle: "झूठी चेतावनियों को रोकने के लिए एआई को अपनी स्थिति की जानकारी दें।",
        activitySelect: "वर्तमान गतिविधि",
        actHiking: "पहाड़ पर चढ़ना / हाइकिंग",
        actExploring: "शहर भ्रमण / दर्शनीय स्थल",
        actSwimming: "जल क्रीड़ा / तैराकी",
        actResting: "आराम / होटल में",
        actTransit: "यात्रा में / गाड़ी चलाना",
        logActivityBtn: "सक्रिय स्थिति अपडेट करें",
        privacyTitle: "गोपनीयता और डेटा एन्क्रिप्शन",
        privacySubtitle: "आपका डेटा स्थानीय स्तर पर सैंडबॉक्स एन्क्रिप्शन से सुरक्षित है।",
        privacyText: "आपके व्यक्तिगत विवरण, लाइव निर्देशांक और गतिविधि लॉग एन्क्रिप्ट किए गए हैं। स्थान इतिहास 48 घंटों में स्वतः मिटा दिया जाता है। सक्रिय एसओएस के दौरान केवल सत्यापित आपातकालीन विभाग ही इसे देख सकते हैं।",
        wearableTitle: "स्मार्ट वियरेबल डिवाइस एकीकरण",
        wearableSubtitle: "उच्च जोखिम वाले क्षेत्रों में महत्वपूर्ण संकेतों की निगरानी के लिए स्मार्टवॉच लिंक करें।",
        wearablePairBtn: "स्मार्टवॉच पेयर करें",
        wearableUnpairBtn: "डिवाइस डिस्कनेक्ट करें",
        wearableStatusConnected: "वियरेबल सक्रिय: सिंक किया गया",
        wearableSelectLabel: "डिवाइस चुनें:",
        wearableHighRiskMode: "उच्च जोखिम भू-बाड़ स्वचालन",
        wearableHighRiskDesc: "गिरने का पता लगाने या दिल की धड़कन बढ़ने पर स्वचालित आपातकालीन ट्रिगर सक्षम करें।",
        vaultTitle: "सुरक्षित डेटाबेस एन्क्रिप्शन वॉल्ट",
        vaultSubtitle: "अस्थायी डेटा भंडारण का वास्तविक समय एन्क्रिप्शन ऑडिट।",
        vaultInspectBtn: "सुरक्षा वॉल्ट का निरीक्षण करें",
        vaultLabelRaw: "एन्क्रिप्टेड स्टोरेज (AES-256 नकली साइफर):",
        vaultLabelDecrypted: "अधिकृत डिक्रिप्टेड प्लेनटेक्स्ट:",
        
        // Admin
        adminConsole: "कमांड और नियंत्रण केंद्र",
        adminSubtitle: "वास्तविक समय आपातकालीन निगरानी, भू-बाड़ (Geofence) स्थिति और एआई चेतावनी लॉग।",
        metricTourists: "सक्रिय पर्यटक",
        metricSOS: "सक्रिय आपातकाल",
        metricRisk: "एआई खतरे की चेतावनी",
        metricIndex: "क्षेत्रीय सुरक्षा स्कोर",
        liveSosFeed: "लाइव आपातकालीन प्रेषण",
        noSosAlerts: "कोई सक्रिय आपातकाल नहीं। प्रणाली सामान्य रूप से कार्यरत है।",
        dispatchBtn: "मददगार रवाना करें",
        resolveBtn: "मामला सुलझाएं और बंद करें",
        aiLogs: "एआई व्यवहार चेतावनी इतिहास",
        aiAnalysisActive: "एआई इंजन टेलीमेट्री का विश्लेषण कर रहा है...",
        touristDirectory: "पर्यटक सुरक्षा रजिस्ट्री",
        exportReport: "रिपोर्ट निर्यात करें",
        sirenBtn: "🔊 सायरन की आवाज़",
        mapLegend: "इंटरएक्टिव जियोफेंस और ट्रैकर मैप",
        mapLabelSeaside: "सीसाइड रिसॉर्ट",
        mapLabelCentral: "केंद्रीय शहर क्षेत्र",
        mapLabelMountain: "पहाड़ की चोटी",
        mapLabelCanyon: "उच्च जोखिम वाली घाटी",
        mapLabelMarina: "डीप वाटर मरीना",
        dispatchSub: "सक्रिय SOS कॉल करने वालों के साथ सीधा समन्वय चैनल।",
        exportSub: "सुरक्षा सूचकांक आँकड़ों की समीक्षा करें और परिचालन लॉग डाउनलोड करें।",
        chartIncidents: "प्रकार के अनुसार घटनाएं",
        chartSafety: "सुरक्षा स्थिति वितरण",
        btnDownloadCsv: "CSV रजिस्ट्री डाउनलोड करें",
        btnDownloadTxt: "ऑडिट टेक्स्ट लॉग डाउनलोड करें",
        kycTitle: "🪪 KYC पहचान सत्यापन कतार",
        kycSubtitle: "पर्यटक पहचान प्रस्तुतियों की समीक्षा, अनुमोदन या अस्वीकार करें।",
        kycBtnRefresh: "🔄 रीफ्रेश करें",
        kycSearchPlace: "🔍 नाम या पासपोर्ट खोजें...",
        kycFilterAll: "सभी",
        kycFilterPending: "लंबित",
        kycFilterVerified: "सत्यापित",
        kycFilterRejected: "अस्वीकृत",
        kycFilterManual: "मैनुअल समीक्षा",
        kycThId: "पर्यटक आईडी",
        kycThName: "पूरा नाम",
        kycThPassport: "पासपोर्ट संख्या",
        kycThSubmitted: "जमा किया गया",
        kycThOcr: "OCR स्थिति",
        kycThKyc: "KYC स्थिति",
        kycThActions: "कार्रवाइयां",
        kycLoading: "KYC प्रस्तुतियाँ लोड हो रही हैं...",
        triggerSosSub: "ट्रिगर करने के लिए क्लिक करें",
        sosTransmitting: "संकट टेलीमेट्री संचारित हो रहा है...",
        notePlaceholder: "आपातकालीन नोट या कस्टम स्थिति अपडेट लिखें (वैकल्पिक)...",
        kycDetailNameLbl: "पूरा नाम",
        kycDetailPassLbl: "पासपोर्ट संख्या",
        kycDetailDobLbl: "जन्म तिथि",
        kycDetailNatLbl: "राष्ट्रीयता",
        kycDetailExpLbl: "समाप्ति तिथि",
        kycDetailIssLbl: "जारीकर्ता देश",
        kycDetailNoOcr: "कोई OCR डेटा उपलब्ध नहीं है।",
        kycBtnView: "देखें →",
        viewMap: "लाइव सुरक्षा मानचित्र",
        mapLegend: "इंटरैक्टिव जियोफेंस और ट्रैकर मानचित्र",
        searchPlaceholder: "आईडी, नाम या राष्ट्रीयता से खोजें...",
        closeDetails: "पैनल बंद करें"
      }
    },

    // Initial mock tourist database
    initialTourists: [
      {
        id: "TSMS-1084",
        fullName: "Sarah Jenkins",
        nationality: "United Kingdom",
        passportNo: "GBR-908123A",
        visaNo: "V-98741029",
        visaExpiry: "2026-12-15",
        emergencyContactName: "David Jenkins",
        emergencyContactPhone: "+44 7700 900077",
        status: "Safe", // Safe, Distress, Warning, Inactive
        activity: "Exploring / Sightseeing",
        x: 180, // SVG map X position
        y: 120, // SVG map Y position
        checkinHistory: ["Hotel Royal Check-in (09:00 AM)", "City Museum check-in (11:30 AM)", "Central Bazaar walk (02:15 PM)"],
        heartRate: 72,
        speed: 4, // km/h
        battery: 88,
        lastUpdated: "Just now"
      },
      {
        id: "TSMS-2041",
        fullName: "Akira Tanaka",
        nationality: "Japan",
        passportNo: "JPN-556108Z",
        visaNo: "V-10294857",
        visaExpiry: "2027-01-20",
        emergencyContactName: "Yuki Tanaka",
        emergencyContactPhone: "+81 90 1234 5678",
        status: "Warning",
        activity: "Mountain Trekking / Hiking",
        x: 420,
        y: 220,
        checkinHistory: ["Base Camp registration (07:00 AM)", "Ridge trail entry (10:15 AM)"],
        heartRate: 118,
        speed: 1.5,
        battery: 23, // Low battery! Triggered AI warning
        lastUpdated: "3 mins ago"
      },
      {
        id: "TSMS-3092",
        fullName: "Carlos Gomez",
        nationality: "Spain",
        passportNo: "ESP-440182K",
        visaNo: "V-30491827",
        visaExpiry: "2026-09-08",
        emergencyContactName: "Maria Gomez",
        emergencyContactPhone: "+34 600 123 456",
        status: "Safe",
        activity: "Resting / At Hotel",
        x: 220,
        y: 350,
        checkinHistory: ["Seaside Resort Check-in (03:00 PM)", "Dinner at Bistro (08:30 PM)"],
        heartRate: 64,
        speed: 0,
        battery: 98,
        lastUpdated: "12 mins ago"
      },
      {
        id: "TSMS-4015",
        fullName: "Amara Diop",
        nationality: "Senegal",
        passportNo: "SEN-112288H",
        visaNo: "V-55648391",
        visaExpiry: "2026-11-30",
        emergencyContactName: "Lamine Diop",
        emergencyContactPhone: "+221 77 123 45 67",
        status: "Safe",
        activity: "Water Sports / Swimming",
        x: 550,
        y: 410,
        checkinHistory: ["Beach Club entry (10:00 AM)", "Jet Ski booking (11:00 AM)"],
        heartRate: 98,
        speed: 18, // Moving on water!
        battery: 74,
        lastUpdated: "5 mins ago"
      },
      {
        id: "TSMS-5099",
        fullName: "Chloe Dubois",
        nationality: "France",
        passportNo: "FRA-776655L",
        visaNo: "V-88294018",
        visaExpiry: "2026-08-22",
        emergencyContactName: "Pierre Dubois",
        emergencyContactPhone: "+33 6 1234 5678",
        status: "Inactive", // Hasn't moved, simulated warning trigger
        activity: "Mountain Trekking / Hiking",
        x: 480,
        y: 110,
        checkinHistory: ["Canyon Trail Gate (Yesterday 02:00 PM)"],
        heartRate: 0, // No telemetry data! Inactive status.
        speed: 0,
        battery: 2,
        lastUpdated: "2 hours ago"
      }
    ],

    // Types of emergency alerts
    sosTypes: [
      { id: "medical", labelKey: "sosMedical", icon: "🚑", color: "#ef4444" },
      { id: "accident", labelKey: "sosAccident", icon: "🚗", color: "#f59e0b" },
      { id: "security", labelKey: "sosSecurity", icon: "👮", color: "#3b82f6" },
      { id: "other", labelKey: "sosOther", icon: "⚠️", color: "#8b5cf6" }
    ],

    // Types of activities
    activities: [
      { id: "hiking", labelKey: "actHiking", icon: "🥾" },
      { id: "exploring", labelKey: "actExploring", icon: "📸" },
      { id: "swimming", labelKey: "actSwimming", icon: "🏊" },
      { id: "resting", labelKey: "actResting", icon: "🏨" },
      { id: "transit", labelKey: "actTransit", icon: "🚗" }
    ],

    // Initial past SOS records
    initialIncidents: [
      {
        id: "INC-9912",
        touristId: "TSMS-1084",
        touristName: "Sarah Jenkins",
        type: "Medical Emergency",
        timestamp: "2026-06-29 14:32",
        location: "Central Market Square",
        status: "Resolved",
        details: "Tourist reported severe dehydration. Emergency paramedics dispatched. Patient treated on-site and cleared."
      },
      {
        id: "INC-9911",
        touristId: "TSMS-3092",
        touristName: "Carlos Gomez",
        type: "Security Threat / Theft",
        timestamp: "2026-06-28 19:10",
        location: "Metro Station North Line",
        status: "Resolved",
        details: "Reported stolen passport wallet. Metro transit security intercepted suspect. Wallet returned; incident closed."
      }
    ],

    // Initial pre-loaded AI Risk logs
    initialAiAlerts: [
      {
        timestamp: "10:48 AM",
        touristId: "TSMS-2041",
        touristName: "Akira Tanaka",
        level: "Warning", // Warning, Danger
        message: "Battery level below 25% in remote alpine wilderness geofence. High communication loss risk.",
        status: "Active"
      },
      {
        timestamp: "08:57 AM",
        touristId: "TSMS-5099",
        touristName: "Chloe Dubois",
        level: "Danger",
        message: "Telemetry disconnect. Zero velocity, zero heart-rate data for 120 minutes. Remote canyon zone.",
        status: "Active"
      },
      {
        timestamp: "07:15 AM",
        touristId: "TSMS-4015",
        touristName: "Amara Diop",
        level: "Info",
        message: "Entered coastal speedway geofence. Speed matches boat telemetry.",
        status: "Cleared"
      }
    ]
  };

  // Attach to window
  window.TSMS_MOCK_DATA = TSMS_MOCK_DATA;
})();
